import {
  Activity,
  AlarmClock,
  Apple,
  Baby,
  Bath,
  Battery,
  Beer,
  Bed,
  Bike,
  BookOpen,
  Brain,
  Briefcase,
  Building2,
  Calculator,
  Calendar,
  CalendarCheck,
  Camera,
  Carrot,
  CheckCircle2,
  CigaretteOff,
  Clock,
  CloudRain,
  Coffee,
  Coins,
  Cookie,
  CreditCard,
  Dices,
  Dog,
  DollarSign,
  Droplet,
  Dumbbell,
  Egg,
  Film,
  Fish,
  Flame,
  Flower2,
  Footprints,
  Gamepad2,
  Gift,
  GlassWater,
  Globe,
  GraduationCap,
  Guitar,
  Hammer,
  Headphones,
  HeartPulse,
  Home,
  IceCreamCone,
  Landmark,
  Languages,
  Laptop,
  Leaf,
  Lightbulb,
  ListTodo,
  Mail,
  MessageSquare,
  Milk,
  Monitor,
  Moon,
  Mountain,
  Music,
  Notebook,
  Palette,
  PawPrint,
  Paintbrush,
  Pencil,
  PenLine,
  PersonStanding,
  Phone,
  Piano,
  Pill,
  PiggyBank,
  Pizza,
  Presentation,
  Puzzle,
  Receipt,
  Recycle,
  Salad,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  ShowerHead,
  Smartphone,
  Smile,
  Snowflake,
  Sparkles,
  Sprout,
  Star,
  Stethoscope,
  Sun,
  Sunrise,
  Sunset,
  Syringe,
  Target,
  Timer,
  Trash2,
  Trees,
  TrendingDown,
  TrendingUp,
  Trophy,
  Tv,
  User,
  Users,
  Utensils,
  Wallet,
  Waves,
  Weight,
  Wine,
  Wrench,
  type LucideIcon,
} from 'lucide-react'

interface IconoHabito {
  nombre: string
  Icon: LucideIcon
  /** Palabras clave en español para el buscador (además del nombre del ícono). */
  etiquetas: string[]
}

export const ICONOS_HABITO: IconoHabito[] = [
  { nombre: 'Sparkles', Icon: Sparkles, etiquetas: ['brillo', 'especial', 'magia'] },
  { nombre: 'HeartPulse', Icon: HeartPulse, etiquetas: ['salud', 'corazón', 'pulso', 'médico'] },
  { nombre: 'Dumbbell', Icon: Dumbbell, etiquetas: ['ejercicio', 'gimnasio', 'pesas', 'entrenar', 'fuerza'] },
  { nombre: 'Apple', Icon: Apple, etiquetas: ['comida', 'fruta', 'alimentación', 'manzana', 'dieta'] },
  { nombre: 'Droplet', Icon: Droplet, etiquetas: ['agua', 'gota', 'hidratación'] },
  { nombre: 'GlassWater', Icon: GlassWater, etiquetas: ['agua', 'vaso', 'beber', 'hidratación'] },
  { nombre: 'Moon', Icon: Moon, etiquetas: ['dormir', 'noche', 'descanso', 'sueño'] },
  { nombre: 'Sun', Icon: Sun, etiquetas: ['mañana', 'día', 'sol', 'despertar'] },
  { nombre: 'Sunrise', Icon: Sunrise, etiquetas: ['amanecer', 'madrugar', 'mañana'] },
  { nombre: 'Sunset', Icon: Sunset, etiquetas: ['atardecer', 'tarde', 'noche'] },
  { nombre: 'BookOpen', Icon: BookOpen, etiquetas: ['leer', 'libro', 'lectura', 'estudio'] },
  { nombre: 'PenLine', Icon: PenLine, etiquetas: ['escribir', 'planificar', 'notas'] },
  { nombre: 'Pencil', Icon: Pencil, etiquetas: ['escribir', 'lápiz', 'dibujar', 'estudio'] },
  { nombre: 'Notebook', Icon: Notebook, etiquetas: ['cuaderno', 'diario', 'anotar', 'estudio'] },
  { nombre: 'Brain', Icon: Brain, etiquetas: ['meditar', 'mente', 'concentración', 'mental'] },
  { nombre: 'Wallet', Icon: Wallet, etiquetas: ['dinero', 'billetera', 'finanzas', 'ahorro'] },
  { nombre: 'DollarSign', Icon: DollarSign, etiquetas: ['dinero', 'finanzas', 'plata'] },
  { nombre: 'Coins', Icon: Coins, etiquetas: ['dinero', 'monedas', 'ahorro', 'finanzas'] },
  { nombre: 'CreditCard', Icon: CreditCard, etiquetas: ['tarjeta', 'gastos', 'finanzas', 'pagos'] },
  { nombre: 'Receipt', Icon: Receipt, etiquetas: ['gastos', 'recibo', 'finanzas', 'presupuesto'] },
  { nombre: 'Landmark', Icon: Landmark, etiquetas: ['banco', 'finanzas', 'ahorro'] },
  { nombre: 'PiggyBank', Icon: PiggyBank, etiquetas: ['ahorrar', 'ahorro', 'chanchito', 'finanzas'] },
  { nombre: 'TrendingUp', Icon: TrendingUp, etiquetas: ['trading', 'inversión', 'progreso', 'crecimiento'] },
  { nombre: 'TrendingDown', Icon: TrendingDown, etiquetas: ['trading', 'gastos', 'bajar', 'reducir'] },
  { nombre: 'Briefcase', Icon: Briefcase, etiquetas: ['trabajo', 'oficina', 'laboral'] },
  { nombre: 'Building2', Icon: Building2, etiquetas: ['trabajo', 'oficina', 'empresa'] },
  { nombre: 'Presentation', Icon: Presentation, etiquetas: ['trabajo', 'presentación', 'reunión'] },
  { nombre: 'ListTodo', Icon: ListTodo, etiquetas: ['tareas', 'planificar', 'lista', 'productividad'] },
  { nombre: 'CheckCircle2', Icon: CheckCircle2, etiquetas: ['completado', 'tareas', 'productividad'] },
  { nombre: 'Calendar', Icon: Calendar, etiquetas: ['calendario', 'planificar', 'agenda'] },
  { nombre: 'CalendarCheck', Icon: CalendarCheck, etiquetas: ['planificar', 'agenda', 'organizar'] },
  { nombre: 'Mail', Icon: Mail, etiquetas: ['correo', 'email', 'trabajo'] },
  { nombre: 'MessageSquare', Icon: MessageSquare, etiquetas: ['mensajes', 'comunicación', 'chat'] },
  { nombre: 'Phone', Icon: Phone, etiquetas: ['llamar', 'teléfono', 'comunicación'] },
  { nombre: 'Smartphone', Icon: Smartphone, etiquetas: ['celular', 'pantalla', 'menos pantalla'] },
  { nombre: 'Monitor', Icon: Monitor, etiquetas: ['computadora', 'pantalla', 'trabajo'] },
  { nombre: 'Tv', Icon: Tv, etiquetas: ['televisión', 'pantalla', 'menos pantalla'] },
  { nombre: 'Home', Icon: Home, etiquetas: ['casa', 'hogar'] },
  { nombre: 'Trash2', Icon: Trash2, etiquetas: ['basura', 'limpieza', 'orden', 'hogar'] },
  { nombre: 'Hammer', Icon: Hammer, etiquetas: ['arreglos', 'hogar', 'reparar'] },
  { nombre: 'Wrench', Icon: Wrench, etiquetas: ['arreglos', 'hogar', 'mantenimiento'] },
  { nombre: 'Lightbulb', Icon: Lightbulb, etiquetas: ['idea', 'ahorro de luz', 'hogar'] },
  { nombre: 'ShowerHead', Icon: ShowerHead, etiquetas: ['ducha', 'higiene', 'baño'] },
  { nombre: 'Bath', Icon: Bath, etiquetas: ['baño', 'higiene', 'relajación'] },
  { nombre: 'User', Icon: User, etiquetas: ['personal', 'yo'] },
  { nombre: 'Users', Icon: Users, etiquetas: ['familia', 'amigos', 'social'] },
  { nombre: 'Baby', Icon: Baby, etiquetas: ['bebé', 'hijos', 'familia'] },
  { nombre: 'PawPrint', Icon: PawPrint, etiquetas: ['mascota', 'perro', 'gato'] },
  { nombre: 'Dog', Icon: Dog, etiquetas: ['perro', 'mascota', 'pasear'] },
  { nombre: 'Gift', Icon: Gift, etiquetas: ['regalo', 'celebrar'] },
  { nombre: 'Leaf', Icon: Leaf, etiquetas: ['naturaleza', 'planta', 'bienestar'] },
  { nombre: 'Sprout', Icon: Sprout, etiquetas: ['planta', 'jardín', 'crecer'] },
  { nombre: 'Flower2', Icon: Flower2, etiquetas: ['flor', 'jardín', 'naturaleza'] },
  { nombre: 'Trees', Icon: Trees, etiquetas: ['naturaleza', 'aire libre', 'caminar'] },
  { nombre: 'Mountain', Icon: Mountain, etiquetas: ['montaña', 'caminata', 'aire libre'] },
  { nombre: 'CloudRain', Icon: CloudRain, etiquetas: ['lluvia', 'clima'] },
  { nombre: 'Snowflake', Icon: Snowflake, etiquetas: ['frío', 'invierno', 'clima'] },
  { nombre: 'Recycle', Icon: Recycle, etiquetas: ['reciclar', 'medio ambiente', 'ecología'] },
  { nombre: 'Smile', Icon: Smile, etiquetas: ['ánimo', 'felicidad', 'bienestar'] },
  { nombre: 'Coffee', Icon: Coffee, etiquetas: ['café', 'mate', 'desayuno'] },
  { nombre: 'CigaretteOff', Icon: CigaretteOff, etiquetas: ['no fumar', 'evitar', 'dejar'] },
  { nombre: 'Wine', Icon: Wine, etiquetas: ['alcohol', 'evitar', 'vino', 'límite'] },
  { nombre: 'Beer', Icon: Beer, etiquetas: ['alcohol', 'evitar', 'cerveza', 'límite'] },
  { nombre: 'Pill', Icon: Pill, etiquetas: ['medicación', 'remedio', 'salud'] },
  { nombre: 'Syringe', Icon: Syringe, etiquetas: ['salud', 'médico', 'vacuna'] },
  { nombre: 'Stethoscope', Icon: Stethoscope, etiquetas: ['médico', 'salud', 'consulta'] },
  { nombre: 'ShieldCheck', Icon: ShieldCheck, etiquetas: ['protección', 'seguridad', 'salud'] },
  { nombre: 'Activity', Icon: Activity, etiquetas: ['actividad', 'salud', 'ejercicio', 'pulso'] },
  { nombre: 'Clock', Icon: Clock, etiquetas: ['tiempo', 'hora', 'reloj'] },
  { nombre: 'AlarmClock', Icon: AlarmClock, etiquetas: ['despertador', 'madrugar', 'alarma'] },
  { nombre: 'Timer', Icon: Timer, etiquetas: ['cronómetro', 'tiempo', 'contador'] },
  { nombre: 'Bed', Icon: Bed, etiquetas: ['dormir', 'cama', 'descanso'] },
  { nombre: 'Footprints', Icon: Footprints, etiquetas: ['caminar', 'pasos', 'ejercicio'] },
  { nombre: 'PersonStanding', Icon: PersonStanding, etiquetas: ['postura', 'estirar', 'ejercicio'] },
  { nombre: 'Weight', Icon: Weight, etiquetas: ['peso', 'pesas', 'ejercicio'] },
  { nombre: 'Bike', Icon: Bike, etiquetas: ['bicicleta', 'ciclismo', 'ejercicio'] },
  { nombre: 'Waves', Icon: Waves, etiquetas: ['nadar', 'natación', 'ejercicio'] },
  { nombre: 'Trophy', Icon: Trophy, etiquetas: ['logro', 'meta', 'competencia'] },
  { nombre: 'Target', Icon: Target, etiquetas: ['meta', 'objetivo', 'foco'] },
  { nombre: 'Flame', Icon: Flame, etiquetas: ['racha', 'energía', 'motivación'] },
  { nombre: 'Star', Icon: Star, etiquetas: ['favorito', 'importante', 'logro'] },
  { nombre: 'Utensils', Icon: Utensils, etiquetas: ['comida', 'comer', 'alimentación'] },
  { nombre: 'Salad', Icon: Salad, etiquetas: ['ensalada', 'saludable', 'alimentación', 'dieta'] },
  { nombre: 'Carrot', Icon: Carrot, etiquetas: ['verdura', 'alimentación', 'saludable'] },
  { nombre: 'Egg', Icon: Egg, etiquetas: ['huevo', 'desayuno', 'alimentación'] },
  { nombre: 'Fish', Icon: Fish, etiquetas: ['pescado', 'alimentación', 'comida'] },
  { nombre: 'Milk', Icon: Milk, etiquetas: ['leche', 'lácteos', 'alimentación'] },
  { nombre: 'Cookie', Icon: Cookie, etiquetas: ['dulce', 'evitar', 'golosina'] },
  { nombre: 'IceCreamCone', Icon: IceCreamCone, etiquetas: ['helado', 'dulce', 'evitar'] },
  { nombre: 'Pizza', Icon: Pizza, etiquetas: ['comida rápida', 'evitar', 'pizza'] },
  { nombre: 'GraduationCap', Icon: GraduationCap, etiquetas: ['estudio', 'universidad', 'aprender'] },
  { nombre: 'Languages', Icon: Languages, etiquetas: ['idioma', 'inglés', 'estudio'] },
  { nombre: 'Calculator', Icon: Calculator, etiquetas: ['matemática', 'números', 'estudio'] },
  { nombre: 'Globe', Icon: Globe, etiquetas: ['mundo', 'geografía', 'viajar', 'idioma'] },
  { nombre: 'Laptop', Icon: Laptop, etiquetas: ['computadora', 'trabajo', 'estudio'] },
  { nombre: 'Music', Icon: Music, etiquetas: ['música', 'instrumento', 'hobby'] },
  { nombre: 'Guitar', Icon: Guitar, etiquetas: ['guitarra', 'música', 'instrumento'] },
  { nombre: 'Piano', Icon: Piano, etiquetas: ['piano', 'música', 'instrumento'] },
  { nombre: 'Headphones', Icon: Headphones, etiquetas: ['música', 'podcast', 'audio'] },
  { nombre: 'Camera', Icon: Camera, etiquetas: ['fotografía', 'foto', 'hobby'] },
  { nombre: 'Film', Icon: Film, etiquetas: ['película', 'cine', 'video'] },
  { nombre: 'Palette', Icon: Palette, etiquetas: ['arte', 'pintar', 'dibujar', 'creatividad'] },
  { nombre: 'Paintbrush', Icon: Paintbrush, etiquetas: ['pintar', 'arte', 'creatividad'] },
  { nombre: 'Gamepad2', Icon: Gamepad2, etiquetas: ['videojuegos', 'jugar', 'hobby'] },
  { nombre: 'Puzzle', Icon: Puzzle, etiquetas: ['rompecabezas', 'juego', 'mental'] },
  { nombre: 'Dices', Icon: Dices, etiquetas: ['juego', 'dados', 'hobby'] },
  { nombre: 'ShoppingBag', Icon: ShoppingBag, etiquetas: ['compras', 'gastos'] },
  { nombre: 'ShoppingCart', Icon: ShoppingCart, etiquetas: ['compras', 'supermercado', 'gastos'] },
  { nombre: 'Battery', Icon: Battery, etiquetas: ['energía', 'descanso', 'recargar'] },
]

const RANGO_DIACRITICOS = new RegExp('[' + String.fromCharCode(0x0300) + '-' + String.fromCharCode(0x036f) + ']', 'g')

const NORMALIZAR = (texto: string) =>
  texto
    .toLowerCase()
    .normalize('NFD')
    .replace(RANGO_DIACRITICOS, '')

/** Filtra el catálogo por nombre o palabras clave en español (sin distinguir mayúsculas/acentos). */
export function buscarIconos(consulta: string): IconoHabito[] {
  const q = NORMALIZAR(consulta.trim())
  if (!q) return ICONOS_HABITO
  return ICONOS_HABITO.filter(
    (i) => NORMALIZAR(i.nombre).includes(q) || i.etiquetas.some((e) => NORMALIZAR(e).includes(q)),
  )
}

const MAPA_ICONOS = new Map(ICONOS_HABITO.map((i) => [i.nombre, i.Icon]))

export function obtenerIcono(nombre: string): LucideIcon {
  return MAPA_ICONOS.get(nombre) ?? Sparkles
}

export const ICONO_POR_DEFECTO = 'Sparkles'
