import {
  AlarmClock,
  Apple,
  Bed,
  Bike,
  BookOpen,
  Brain,
  Briefcase,
  Camera,
  CigaretteOff,
  Clock,
  Coffee,
  Dog,
  Droplet,
  Dumbbell,
  Flame,
  Footprints,
  Gamepad2,
  GlassWater,
  GraduationCap,
  Headphones,
  HeartPulse,
  Home,
  Languages,
  Laptop,
  Leaf,
  Moon,
  Music,
  Palette,
  PenLine,
  Pill,
  PiggyBank,
  Recycle,
  Salad,
  Smile,
  Sparkles,
  Sprout,
  Star,
  Stethoscope,
  Sun,
  Target,
  TrendingUp,
  User,
  Utensils,
  Wallet,
  type LucideIcon,
} from 'lucide-react'

export const ICONOS_HABITO: { nombre: string; Icon: LucideIcon }[] = [
  { nombre: 'Sparkles', Icon: Sparkles },
  { nombre: 'HeartPulse', Icon: HeartPulse },
  { nombre: 'Dumbbell', Icon: Dumbbell },
  { nombre: 'Apple', Icon: Apple },
  { nombre: 'Droplet', Icon: Droplet },
  { nombre: 'GlassWater', Icon: GlassWater },
  { nombre: 'Moon', Icon: Moon },
  { nombre: 'Sun', Icon: Sun },
  { nombre: 'BookOpen', Icon: BookOpen },
  { nombre: 'PenLine', Icon: PenLine },
  { nombre: 'Brain', Icon: Brain },
  { nombre: 'Wallet', Icon: Wallet },
  { nombre: 'TrendingUp', Icon: TrendingUp },
  { nombre: 'Briefcase', Icon: Briefcase },
  { nombre: 'Home', Icon: Home },
  { nombre: 'User', Icon: User },
  { nombre: 'Leaf', Icon: Leaf },
  { nombre: 'Smile', Icon: Smile },
  { nombre: 'Coffee', Icon: Coffee },
  { nombre: 'CigaretteOff', Icon: CigaretteOff },
  { nombre: 'Clock', Icon: Clock },
  { nombre: 'Footprints', Icon: Footprints },
  { nombre: 'Bike', Icon: Bike },
  { nombre: 'Music', Icon: Music },
  { nombre: 'Camera', Icon: Camera },
  { nombre: 'Palette', Icon: Palette },
  { nombre: 'Laptop', Icon: Laptop },
  { nombre: 'Utensils', Icon: Utensils },
  { nombre: 'Salad', Icon: Salad },
  { nombre: 'Pill', Icon: Pill },
  { nombre: 'Stethoscope', Icon: Stethoscope },
  { nombre: 'Bed', Icon: Bed },
  { nombre: 'AlarmClock', Icon: AlarmClock },
  { nombre: 'Target', Icon: Target },
  { nombre: 'Flame', Icon: Flame },
  { nombre: 'Star', Icon: Star },
  { nombre: 'Dog', Icon: Dog },
  { nombre: 'PiggyBank', Icon: PiggyBank },
  { nombre: 'Recycle', Icon: Recycle },
  { nombre: 'Sprout', Icon: Sprout },
  { nombre: 'GraduationCap', Icon: GraduationCap },
  { nombre: 'Languages', Icon: Languages },
  { nombre: 'Headphones', Icon: Headphones },
  { nombre: 'Gamepad2', Icon: Gamepad2 },
]

const MAPA_ICONOS = new Map(ICONOS_HABITO.map((i) => [i.nombre, i.Icon]))

export function obtenerIcono(nombre: string): LucideIcon {
  return MAPA_ICONOS.get(nombre) ?? Sparkles
}

export const ICONO_POR_DEFECTO = 'Sparkles'
